import { DeckTemplateSchema, type DeckTemplate } from '@presentation-studio/schema';

export const brochureEnterprise: DeckTemplate = DeckTemplateSchema.parse({
  id: 'brochure-enterprise',
  name: 'Enterprise Brochure',
  description:
    'Brochure comercial para clientes enterprise. Comunica quién es la empresa, qué hace, en qué industrias opera y por qué elegirla.',
  recommended_audience: 'Clientes enterprise, directores y decision-makers técnicos y de negocio.',
  recommended_slide_count: { min: 8, max: 14, ideal: 11 },
  density_guidance: 'balanced',
  content_guidance: [
    'Usa lenguaje profesional, directo y sin jerga innecesaria.',
    'Cada slide debe tener un mensaje central claro.',
    'Usa métricas concretas cuando sea posible.',
    'El cierre debe tener una llamada a la acción clara.',
  ],
  default_theme: 'magma',
  slide_flow: [
    {
      slide_id: 'cover',
      layout: 'hero-cover',
      purpose: 'Carátula con nombre, propuesta de valor corta y visual principal.',
      required_fields: ['title'],
      optional_fields: ['subtitle', 'images'],
      content_hints: ['Usa una frase de valor corta (máx. 12 palabras).'],
      density: 'minimal',
    },
    {
      slide_id: 'who-we-are',
      layout: 'two-column-text',
      purpose: 'Presentación breve de la empresa.',
      required_fields: ['title', 'body'],
      optional_fields: ['bullets'],
      content_hints: ['Enfatiza años de experiencia, regiones y tipo de clientes.'],
      density: 'balanced',
    },
    {
      slide_id: 'what-we-do',
      layout: 'capabilities-grid',
      purpose: 'Servicios o capacidades principales.',
      required_fields: ['title', 'items'],
      content_hints: ['Usa entre 4 y 6 capabilities con descripciones cortas.'],
      density: 'balanced',
    },
    {
      slide_id: 'industries',
      layout: 'metrics-grid',
      purpose: 'Industrias en las que la empresa tiene experiencia.',
      required_fields: ['title', 'items'],
      content_hints: ['Prefiere nombres cortos de industrias con un detalle clave.'],
      density: 'balanced',
    },
    {
      slide_id: 'process',
      layout: 'process-steps',
      purpose: 'Cómo trabaja la empresa con el cliente.',
      required_fields: ['title', 'items'],
      content_hints: ['Entre 3 y 5 pasos claros.'],
      density: 'balanced',
    },
    {
      slide_id: 'case-studies',
      layout: 'case-study-highlight',
      purpose: 'Referencia rápida a casos de éxito.',
      required_fields: ['title'],
      optional_fields: ['metrics', 'items', 'body'],
      content_hints: ['Incluye al menos una métrica relevante.'],
      density: 'balanced',
    },
    {
      slide_id: 'logo-wall',
      layout: 'logo-wall',
      purpose: 'Clientes destacados.',
      required_fields: ['title', 'logos'],
      content_hints: ['Entre 6 y 12 logos.'],
      density: 'minimal',
    },
    {
      slide_id: 'testimonials',
      layout: 'testimonial-grid',
      purpose: 'Voces de clientes reales.',
      required_fields: ['title', 'items'],
      content_hints: ['Usa 2–3 testimonios con nombre, cargo y empresa.'],
      density: 'balanced',
    },
    {
      slide_id: 'why-us',
      layout: 'metrics-grid',
      purpose: 'Argumentos diferenciales cuantificables.',
      required_fields: ['title', 'metrics'],
      content_hints: ['Usa 3–4 métricas de impacto reales.'],
      density: 'balanced',
    },
    {
      slide_id: 'team',
      layout: 'capabilities-grid',
      purpose: 'Equipo, cultura o enfoque humano.',
      required_fields: ['title'],
      optional_fields: ['body', 'items', 'images'],
      content_hints: ['Un párrafo corto y 3–4 ideas clave.'],
      density: 'balanced',
    },
    {
      slide_id: 'closing-cta',
      layout: 'closing-cta',
      purpose: 'Llamada a la acción y datos de contacto.',
      required_fields: ['title', 'cta'],
      content_hints: ['Agrega email, sitio web o un link concreto.'],
      density: 'minimal',
    },
  ],
});
