import { DeckTemplateSchema, type DeckTemplate } from '@presentation-studio/schema';

export const trainingDeck: DeckTemplate = DeckTemplateSchema.parse({
  id: 'training-deck',
  name: 'Training Deck',
  description: 'Deck de capacitación o formación interna. Estructurado por módulos.',
  recommended_audience: 'Equipos internos, onboarding, formación técnica o de negocio.',
  recommended_slide_count: { min: 8, max: 20, ideal: 14 },
  density_guidance: 'balanced',
  content_guidance: [
    'Cada sección debe tener un objetivo de aprendizaje claro.',
    'Incluye resúmenes y Q&A al final.',
  ],
  default_theme: 'minimal',
  slide_flow: [
    {
      slide_id: 'cover',
      layout: 'hero-cover',
      purpose: 'Portada con título del curso.',
      required_fields: ['title'],
      optional_fields: ['subtitle'],
      density: 'minimal',
    },
    {
      slide_id: 'goals',
      layout: 'capabilities-grid',
      purpose: 'Objetivos de aprendizaje.',
      required_fields: ['title', 'items'],
      density: 'balanced',
    },
    {
      slide_id: 'agenda',
      layout: 'process-steps',
      purpose: 'Módulos del curso.',
      required_fields: ['title', 'items'],
      density: 'balanced',
    },
    {
      slide_id: 'module-intro',
      layout: 'section-divider',
      purpose: 'Separador de módulo.',
      required_fields: ['title'],
      optional_fields: ['subtitle'],
      density: 'minimal',
    },
    {
      slide_id: 'concept',
      layout: 'two-column-text',
      purpose: 'Explicación conceptual.',
      required_fields: ['title', 'body'],
      density: 'balanced',
    },
    {
      slide_id: 'example',
      layout: 'image-left-text-right',
      purpose: 'Ejemplo práctico.',
      required_fields: ['title', 'body'],
      optional_fields: ['images'],
      density: 'balanced',
    },
    {
      slide_id: 'comparison',
      layout: 'comparison-table',
      purpose: 'Comparación entre enfoques.',
      required_fields: ['title', 'items'],
      density: 'balanced',
    },
    {
      slide_id: 'summary',
      layout: 'capabilities-grid',
      purpose: 'Resumen final.',
      required_fields: ['title', 'items'],
      density: 'balanced',
    },
    {
      slide_id: 'closing-cta',
      layout: 'closing-cta',
      purpose: 'Cierre y contacto.',
      required_fields: ['title'],
      optional_fields: ['cta'],
      density: 'minimal',
    },
  ],
});
